### ISSUE TITLE
`cprof` can't handle Khepri?

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/khepri#17]
I'm not sure if that's a bug in Khepri, a side effect of how Khepri transactions work or perhaps a limitation/bug in `cprof` but they don't like each other. While I don't need to profile `khepri:info/0`, I'm a bit concerned that some tooling may struggle with Khepri (`fprof` seems fine so far though)

```
1> cprof:start().
51988
(rabbit@mkuratczyk-a01)2> khepri:info().
Running stores:
  metadata_store
ok
(rabbit@mkuratczyk-a01)3> cprof:stop().
51988
(rabbit@mkuratczyk-a01)4> cprof:analyze().
** exception error: undefined function 'ktx__rabbit_vhost__-with_in_khepri/2-fun-0-__106331979':module_info/1
     in function  cprof:analyse/2 (cprof.erl, line 196)
     in call from cprof:'-analyse/1-lc$^0/1-0-'/2 (cprof.erl, line 178)
     in call from cprof:'-analyse/1-lc$^0/1-0-'/2 (cprof.erl, line 178)
     in call from cprof:analyse/1 (cprof.erl, line 178)
```

**Comment by dumbbell** [comment]
`module_info/{0,1}` are added automatically by the Erlang compiler to all modules when it prepares the Beam assembly.

After talking with Loïc, we decided that the `module_info/{0,1}` were not that useful to everyday uses and they would double the generated module size (and footprint in Ra commands and WAL) for simple transactions. That's why the module generated while extracting a transaction function does not have them.

It's easy to add them back, but we have to make a compromise somewhere. What do you think?

**Comment by mkuratczyk** [comment]
Sounds reasonable. I wasn't aware that this was a known limitation and an explicit trade-off.
