### ISSUE TITLE
Accept binaries as Unix-like paths

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/khepri#92]
Currently a Khepri path is either a native path (a list of atoms, binaries and conditions) or a Unix-like path which is an Erlang string.

Several other Beam languages such as Elixir or Gleam implement strings as Erlang binaries. Therefore, it would be nice to extend Unix-like path to accept binaries as well. This should be even simpler to parse because we don't have to determine if the passed list is a native path or a Unix-like string!

The easy part is to update `khepri_path:from_string/1` to accept and parse binaries. The boring part is to update all function specs... A new type should be introduced to include `khepri_path:path()`, `string()` and `binary()`.

**Comment by the-mikedavis** [comment]
I see a TODO for changing that `path/0` to `node_path/0`: https://github.com/rabbitmq/khepri/blob/686a16012b98b2baf6f71e56da534ae143d30de9/src/khepri_path.erl#L83-L91

What would you think about types like these?

```erl
%% (renamed from `path/0`)
-type node_path() :: [component()].
%% A native path to a node.

-type unix_path() :: string() | binary().
%% A path as a string or binary.

-type path() :: unix_path() | node_path().
%% A path to a node. Either a string, binary, or a native path.
```

**Comment by michaelklishin** [comment]
What constitutes a "native pattern"? I assume a UNIX pattern is slash-separated? If so, `slash_separated` or `fs_like_path` could be slightly more descriptive?

**Comment by the-mikedavis** [comment]
If I understand it correctly, native paths are the internal representation for paths

```erl
[stock, wood, <<"oak">>].
```

and then unix paths are a convenient string-based syntax that can be translated into native paths

```erl
khepri_path:from_string("/:stock/:wood/oak").
%%=> [stock, wood, <<"oak">>]
```

With patterns being a supertype that also allows conditions from `khepri_condition`:

```erl
%% native pattern:
[stock,
 #if_all{conditions = [wood,
                       #if_node_exists{exists = true}]},
 oak].
```

I like the connotations of "unix" and "native" but unix isn't totally perfect because the `:atom` syntax doesn't have an equivalent in unix paths. Maybe there's a good word that describes unix paths as a convenient syntax (similar to "native" implying that native paths are the internal representation)?

**Comment by michaelklishin** [comment]
So they are list paths and slash-separated or filesystem-like paths.

**Comment by dumbbell** [comment]
I created a separate pull request (#94) to handle the redefinition of the `path()` type and how things should be named.
